export const dataHeroEquip = {
    "Name": "DataHeroEquip",
    "Version": 1,
    "Data": [
      {
        "Index": "Stone",
        "Code": 10101,
        "HeroEquipType": 1,
        "TDGunCode": 10101,
        "ModelName": "Stone",
        "QualityItemCode": 1,
        "IconName": "",
        "IconBorderName": "",
        "Power": 0.5,
        "Atk": 1,
        "Def": 0,
        "Agi": 0,
        "Dex": 0,
        "Hp": 0,
        "CrtRate": 0,
        "PowerRise": 0,
        "AtkRise": 0,
        "DefRise": 0,
        "AgiRise": 0,
        "DexRise": 0,
        "HpRise": 0,
        "CrtRateRise": 0,
        "CostUpgrade": 0,
        "CostUpgradeRise": 0
      },
      {
        "Index": "Boomerang",
        "Code": 10201,
        "HeroEquipType": 1,
        "TDGunCode": 10101,
        "ModelName": "Boomerang",
        "QualityItemCode": 1,
        "IconName": "Boomerang_Icon",
        "IconBorderName": "Boomerang_Border",
        "Power": 1,
        "Atk": 2,
        "Def": 0,
        "Agi": 0,
        "Dex": 0,
        "Hp": 0,
        "CrtRate": 0,
        "PowerRise": 0.1,
        "AtkRise": 0.2,
        "DefRise": 0,
        "AgiRise": 0,
        "DexRise": 0,
        "HpRise": 0,
        "CrtRateRise": 0,
        "CostUpgrade": 5,
        "CostUpgradeRise": 1
      },
      {
        "Index": "PeasantClothing",
        "Code": 20101,
        "HeroEquipType": 2,
        "TDGunCode": 0,
        "ModelName": "PeasantClothing",
        "QualityItemCode": 1,
        "IconName": "",
        "IconBorderName": "",
        "Power": 0.5,
        "Atk": 0,
        "Def": 0.5,
        "Agi": 0,
        "Dex": 0,
        "Hp": 0,
        "CrtRate": 0,
        "PowerRise": 0,
        "AtkRise": 0,
        "DefRise": 0,
        "AgiRise": 0,
        "DexRise": 0,
        "HpRise": 0,
        "CrtRateRise": 0,
        "CostUpgrade": 0,
        "CostUpgradeRise": 0
      }
    ]
  }