export const HeroEquipData = [
    {
      "Index": "WP1001",
      "Code": 1001,
      "Type": 1,
      "ModelName": "1001_Model",
      "QualityItemCode": "White",
      "IconName": "1001_Icon",
      "IconBorderName": "1001_IconBorder",
      "Atk": 1,
      "Def": 0,
      "Agi": 0,
      "Dex": 0,
      "Hp": 0,
      "Crt": 0,
      "CrtRate": 0
    },
    {
      "Index": "WP1002",
      "Code": 1002,
      "Type": 1,
      "ModelName": "1002_Model",
      "QualityItemCode": "White",
      "IconName": "1002_Icon",
      "IconBorderName": "1002_IconBorder",
      "Atk": 1,
      "Def": 0,
      "Agi": 0,
      "Dex": 0,
      "Hp": 0,
      "Crt": 0,
      "CrtRate": 0
    },
    {
      "Index": "WP1003",
      "Code": 1003,
      "Type": 1,
      "ModelName": "1003_Model",
      "QualityItemCode": "White",
      "IconName": "1003_Icon",
      "IconBorderName": "1003_IconBorder",
      "Atk": 1,
      "Def": 0,
      "Agi": 0,
      "Dex": 0,
      "Hp": 0,
      "Crt": 0,
      "CrtRate": 0
    },
    {
      "Index": "AR2001",
      "Code": 2001,
      "Type": 2,
      "ModelName": "2001_Model",
      "QualityItemCode": "White",
      "IconName": "2001_Icon",
      "IconBorderName": "2001_IconBorder",
      "Atk": 0,
      "Def": 0,
      "Agi": 0,
      "Dex": 0,
      "Hp": 1,
      "Crt": 0,
      "CrtRate": 0
    },
    {
      "Index": "AR2002",
      "Code": 2002,
      "Type": 2,
      "ModelName": "2002_Model",
      "QualityItemCode": "White",
      "IconName": "2002_Icon",
      "IconBorderName": "2002_IconBorder",
      "Atk": 0,
      "Def": 0,
      "Agi": 0,
      "Dex": 0,
      "Hp": 1,
      "Crt": 0,
      "CrtRate": 0
    },
    {
      "Index": "AR2003",
      "Code": 2003,
      "Type": 2,
      "ModelName": "2003_Model",
      "QualityItemCode": "White",
      "IconName": "2003_Icon",
      "IconBorderName": "2003_IconBorder",
      "Atk": 0,
      "Def": 0,
      "Agi": 0,
      "Dex": 0,
      "Hp": 1,
      "Crt": 0,
      "CrtRate": 0
    },
    {
      "Index": "HM3001",
      "Code": 3001,
      "Type": 3,
      "ModelName": "3001_Model",
      "QualityItemCode": "White",
      "IconName": "3001_Icon",
      "IconBorderName": "3001_IconBorder",
      "Atk": 0,
      "Def": 0,
      "Agi": 0,
      "Dex": 1,
      "Hp": 0,
      "Crt": 0,
      "CrtRate": 0
    },
    {
      "Index": "HM3002",
      "Code": 3002,
      "Type": 3,
      "ModelName": "3002_Model",
      "QualityItemCode": "White",
      "IconName": "3002_Icon",
      "IconBorderName": "3002_IconBorder",
      "Atk": 0,
      "Def": 0,
      "Agi": 0,
      "Dex": 1,
      "Hp": 0,
      "Crt": 0,
      "CrtRate": 0
    },
    {
      "Index": "HM3003",
      "Code": 3003,
      "Type": 3,
      "ModelName": "3003_Model",
      "QualityItemCode": "White",
      "IconName": "3003_Icon",
      "IconBorderName": "3003_IconBorder",
      "Atk": 0,
      "Def": 0,
      "Agi": 0,
      "Dex": 1,
      "Hp": 0,
      "Crt": 0,
      "CrtRate": 0
    }
  ]